services:
  backend:
    build: ./backend
    container_name: musicbridge-api
    ports:
      - "8000:8000"
      - "8080:8080" # Spotify Auth Callback
    env_file:
      - .env
    volumes:
      - ./backend:/app # Hot reload in dev

  frontend:
    build: ./frontend
    container_name: musicbridge-ui
    ports:
      - "80:80"
    depends_on:
      - backend
